services:
  web:
    build: .
    command: gunicorn incidents.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - .:/code
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - TZ=Europe/Kiev
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - TZ=Europe/Kiev
    ports:
      - "5432:5432"
    command: ["docker-entrypoint.sh", "postgres"]

  nginx:
    build: ./nginx
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db-data: